version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angular",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "browser",
    "mongo"
  ]